version: '3.3'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: JustZed32+
      POSTGRES_DB: challengerdb
    ports:
      - "5432:5432"

