CREATE TABLE challenge
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255)                             NOT NULL,
    difficulty  VARCHAR(255)                             NOT NULL,
    area        VARCHAR(255)                             NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expires_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by  INTEGER                                  NOT NULL,
    group_id    INTEGER                                  NOT NULL,
    CONSTRAINT pk_challenge PRIMARY KEY (id)
);

CREATE TABLE challenge_user
(
    challenge_id INTEGER NOT NULL,
    user_id      INTEGER NOT NULL,
    CONSTRAINT pk_challenge_user PRIMARY KEY (challenge_id, user_id)
);

CREATE TABLE chat_user
(
    group_id INTEGER NOT NULL,
    user_id  INTEGER NOT NULL,
    CONSTRAINT pk_chat_user PRIMARY KEY (group_id, user_id)
);

CREATE TABLE groups
(
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    total_tasks_completed INTEGER                                  NOT NULL,
    telegram_id           BIGINT                                   NOT NULL,
    group_name            VARCHAR(50)                              NOT NULL,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stats_id    INTEGER,
    first_name  VARCHAR(50)                              NOT NULL,
    telegram_id BIGINT                                   NOT NULL,
    last_name   VARCHAR(50),
    username    VARCHAR(50),
    coins       INTEGER                                  NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE user_stats
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mindfulness   INTEGER                                  NOT NULL,
    fitness       INTEGER                                  NOT NULL,
    relationships INTEGER                                  NOT NULL,
    finances      INTEGER                                  NOT NULL,
    CONSTRAINT pk_user_stats PRIMARY KEY (id)
);

ALTER TABLE challenge
    ADD CONSTRAINT FK_CHALLENGE_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES "user" (id);

ALTER TABLE challenge
    ADD CONSTRAINT FK_CHALLENGE_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE "user"
    ADD CONSTRAINT FK_USER_ON_STATS FOREIGN KEY (stats_id) REFERENCES user_stats (id);

ALTER TABLE chat_user
    ADD CONSTRAINT fk_chat_user_on_group FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE chat_user
    ADD CONSTRAINT fk_chat_user_on_user FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE challenge_user
    ADD CONSTRAINT fk_chause_on_challenge FOREIGN KEY (challenge_id) REFERENCES challenge (id);

ALTER TABLE challenge_user
    ADD CONSTRAINT fk_chause_on_user FOREIGN KEY (user_id) REFERENCES "user" (id);